local icons = {
  kind = {
    Array = '',
    Boolean = '',
    Class = '',
    Color = '',
    Constant = '',
    Constructor = '',
    Enum = '',
    EnumMember = '',
    Event = '',
    Field = '',
    File = '',
    Folder = '󰉋',
    Function = '',
    Interface = '',
    Key = '',
    Keyword = '',
    Method = '',
    Module = '',
    Namespace = '',
    Null = '󰟢',
    Number = '',
    Object = '',
    Operator = '',
    Package = '',
    Property = '',
    Reference = '',
    Snippet = '',
    String = '',
    Struct = '',
    Text = '',
    TypeParameter = '',
    Unit = '',
    Value = '',
    Variable = '',
  },
  git = {
    LineAdded = '',
    LineModified = '',
    LineRemoved = '',
    FileDeleted = '',
    FileIgnored = '◌',
    FileRenamed = '',
    FileStaged = 'S',
    FileUnmerged = '',
    FileUnstaged = '',
    FileUntracked = 'U',
    Diff = '',
    Repo = '',
    Octoface = '',
    Branch = '',
  },
  ui = {
    ArrowCircleDown = '',
    ArrowCircleLeft = '',
    ArrowCircleRight = '',
    ArrowCircleUp = '',
    BoldArrowDown = '',
    BoldArrowLeft = '',
    BoldArrowRight = '',
    BoldArrowUp = '',
    BoldClose = '',
    BoldDividerLeft = '',
    BoldDividerRight = '',
    BoldLineLeft = '▎',
    BookMark = '',
    BoxChecked = '',
    Bug = '',
    Stacks = '',
    Scopes = '',
    Watches = '󰂥',
    DebugConsole = '',
    Calendar = '',
    Check = '',
    ChevronRight = '',
    ChevronShortDown = '',
    ChevronShortLeft = '',
    ChevronShortRight = '',
    ChevronShortUp = '',
    Circle = '',
    Close = '󰅖',
    CloudDownload = '',
    Code = '',
    Comment = '',
    Dashboard = '',
    DividerLeft = '',
    DividerRight = '',
    DoubleChevronRight = '»',
    Ellipsis = '',
    EmptyFolder = '',
    EmptyFolderOpen = '',
    File = '',
    FileSymlink = '',
    Files = '',
    FindFile = '󰈞',
    FindText = '󰊄',
    Fire = '',
    Folder = '󰉋',
    FolderOpen = '',
    FolderSymlink = '',
    Forward = '',
    Gear = '',
    History = '',
    Lightbulb = '',
    LineLeft = '▏',
    LineMiddle = '│',
    List = '',
    Lock = '',
    NewFile = '',
    Note = '',
    Package = '',
    Pencil = '󰏫',
    Plus = '',
    Project = '',
    Search = '',
    SignIn = '',
    SignOut = '',
    Tab = '󰌒',
    Table = '',
    Target = '󰀘',
    Telescope = '',
    Text = '',
    Tree = '',
    Triangle = '󰐊',
    TriangleShortArrowDown = '',
    TriangleShortArrowLeft = '',
    TriangleShortArrowRight = '',
    TriangleShortArrowUp = '',
  },
  diagnostics = {
    BoldError = '',
    Error = '',
    BoldWarning = '',
    Warning = '',
    BoldInformation = '',
    Information = '',
    BoldQuestion = '',
    Question = '',
    BoldHint = '',
    Hint = '󰌶',
    Debug = '',
    Trace = '✎',
  },
  misc = {
    Robot = '󰚩',
    Squirrel = '',
    Tag = '',
    Watch = '',
    Smiley = '',
    Package = '',
    CircuitBoard = '',
  },
}

return {
  {
    'nvim-tree/nvim-tree.lua',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    version = '*',
    config = function()
      require('nvim-tree').setup {
        filters = {
          custom = { '^.git$' },
        },
        sync_root_with_cwd = true,
        update_focused_file = {
          enable = true,
          update_root = false,
        },
        view = {
          signcolumn = 'yes',
          adaptive_size = true,
          side = 'left',
          width = 30,
          preserve_window_proportions = true,
        },
        git = {
          enable = true,
          ignore = false,
          show_on_dirs = true,
          show_on_open_dirs = true,
          timeout = 2000,
        },
        modified = {
          enable = true,
          show_on_dirs = true,
          show_on_open_dirs = true,
        },
        diagnostics = {
          enable = true,
          show_on_dirs = true,
          show_on_open_dirs = true,
          debounce_delay = 50,
          severity = {
            min = vim.diagnostic.severity.HINT,
            max = vim.diagnostic.severity.ERROR,
          },
          icons = {
            hint = icons.diagnostics.BoldHint,
            info = icons.diagnostics.BoldInformation,
            warning = icons.diagnostics.BoldWarning,
            error = icons.diagnostics.BoldError,
          },
        },

        filesystem_watchers = {
          enable = true,
        },
        actions = {
          open_file = {
            resize_window = true,
          },
        },
        renderer = {
          root_folder_label = false,
          highlight_git = false,
          highlight_opened_files = 'none',

          indent_markers = {
            enable = false,
          },
          icons = {
            webdev_colors = true,
            git_placement = 'before',
            modified_placement = 'after',
            padding = ' ',
            symlink_arrow = ' ➛ ',
            show = {
              file = true,
              folder = true,
              folder_arrow = true,
              git = true,
              modified = true,
            },
            glyphs = {
              default = icons.ui.Text,
              symlink = icons.ui.FileSymlink,
              bookmark = icons.ui.BookMark,
              modified = icons.git.LineModified,
              folder = {
                arrow_closed = icons.ui.TriangleShortArrowRight,
                arrow_open = icons.ui.TriangleShortArrowDown,
                default = icons.ui.Folder,
                open = icons.ui.FolderOpen,
                empty = icons.ui.EmptyFolder,
                empty_open = icons.ui.EmptyFolderOpen,
                symlink = icons.ui.FolderSymlink,
                symlink_open = icons.ui.FolderOpen,
              },
              git = {
                unstaged = icons.ui.BoldClose,
                staged = icons.git.FileStaged,
                unmerged = icons.git.FileUnmerged,
                renamed = icons.git.FileRenamed,
                untracked = icons.git.FileUntracked,
                deleted = icons.git.FileDeleted,
                ignored = icons.git.FileIgnored,
              },
            },
          },
        },
      }
    end,
  },
}
